### ISSUE TITLE
Feedback on SampleQC usage

### ISSUE THREAD

**Issue by SimoneTiberi** [wmacnair/SampleQC#3] opened 2020-05-13 11:43 UTC
- [x] I noticed that `make_qc_dt` requires `sample_id`, while `embed_sample_to_sample_MMDs` looks for `patient_id`.

- [ ] Running `make_qc_dt` gave this warning: `found 0 mitochondrial genes, which is less than the expected 13 human genes; you may want to check your data`.
I see it looks for gene names in rownames(sce): I'd be nice to specify where gene names have to be stored in the manual.

- [x] Concerning counts/log_counts etc..., do you normalize counts/log_counts or use raw values?

- [x] concerning the html report:
- it'd be great if users could click on plots to get the sample name, e.g., in 'αj  PCA values' plots.
- are QC1 and QC2 supposed to split samples according to their group? in my plot it simply splits samples in 2, but not according to group.
Maybe that's the automatic clustering of samples, according to QC similarity, right ?
If so, then what is the "condition" variable used for?

Code used:
```
rm(list =ls())
library('SampleQC')
library(muscData)

sce = Kang18_8vs8()

# specify the sample_id and condition
sce$sample_id = paste0(sce$ind, sce$stim, paste = "_")
sce$condition = sce$stim

qc_dt   = make_qc_dt(sce)
# gene names are in rownames(sce):
rownames(sce)

# which QC metrics do we want to use? (the most important bit)
qc_names        = c('log_counts', 'log_feats', 'logit_mito')
# which discrete-valued variables do we want to annotate the samples with?
annot_discrete  = c('well_id', 'patient_id', 'condition')
# which continuous-valued variables do we want to annotate the samples with?
annot_cont      = NULL

mmd_list    = calculate_sample_to_sample_MMDs(qc_dt, qc_names, subsample=200, n_times=20, n_cores=16)
mmd_list    = embed_sample_to_sample_MMDs(mmd_list, qc_dt, annot_discrete, annot_cont, n_nhbrs=5)

print(table(mmd_list$mmd_clusts))

set.seed(123)
system.time({
  em_list     = fit_sampleQC(mmd_list, qc_dt, qc_names, K_list=c(1,1,1,1))
})
# Once you've fit everything, you can render an html report and check whether it makes sense.

# define you project name and where you want to save these reports
proj_name   = 'Kang_ex'
save_dir    = '~/Desktop/Will SampleQC/Kang_ex/'
dir.create(save_dir)

# render the report!
make_SampleQC_report(mmd_list, em_list, save_dir, proj_name)
```

**Comment by wmacnair** [comment] 2021-06-05 14:05
Only a couple of these are still relevant:
- I've removed the axis labels from the MMD heatmap
- The mito issue is a duplicate of #10

**Closed by wmacnair** 2021-06-05 14:05 UTC
Labels: enhancement, style
